

spring:
  application:
    name: API-GATEWAY-SERVICE
  main:
    web-application-type: reactive
  cloud:
    config:
      uri: http://localhost:9010
  config:
    import: optional:configserver:http://localhost:9010
server:
  port: 9000

