eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
    register-with-eureka: true # Enable client registration
    fetch-registry: true       # Fetch registry from Eureka server
  instance:
    prefer-ip-address: true    # Use IP address for registration instead of hostname
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true