server:
  port: 8762
spring:
  application:
    name: eureka-server
#  cloud:
#    config:
#      uri: http://localhost:9010
#  config:
#    import: optional:configserver:http://localhost:9010

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false