spring:

  application:
    name: STAKEHOLDER
  cloud:
    config:
      uri: http://localhost:9010
      fail-fast: true
  config:
    import: configserver:http://localhost:9010
server:
  port: 8070
