server:
  port: 9010

spring:
  application:
    name: config-servers
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-repo/config-repo # Replace with your Git repo URL
          clone-on-start: true